##############################################################
# This Playbook initialises a Vault cluster
##############################################################
---
- hosts: all
  vars:
    ca_cert: "{{ playbook_dir }}/ca.crt"
    ca_cert_copy: True
  tasks:
    - include_role:
        name: filters
      tags:
        - always
    - include_role:
        name: vault-env
    - include_role:
        name: vault-init
      run_once: True
